### ISSUE TITLE
??

### ISSUE THREAD

**Issue by validusernameF** [OTAKKATO/ZeroDiscord#37]
it says invalid escape sequence while installing, how do i fix this? my discord is t0asttt. if you decide to DM

i dont have much coding experience so any help would be appreciated

**Comment by I2rys** [comment]
Hello @validusernameF I have sent a fr in your Discord.

**Comment by validusernameF** [comment]
> Hello @validusernameF I have sent a fr in your Discord.

i havent gotten one yet

**Comment by I2rys** [comment]
> > Hello @validusernameF I have sent a fr in your Discord.
> 
> i havent gotten one yet

I already sent a fr. I think you decline my last request and my username in Discord is still **I2rys**
