### ISSUE TITLE
Need some help setting up

### ISSUE THREAD

**Issue by k9in3** [OTAKKATO/ZeroDiscord#38]
Hey, I just need some guidance with the first few steps of setting this up, please get back to me if you can, discord name is hairyarab

**Comment by I2rys** [comment]
Hello @k9in3 I have added you in Discord, please check your friend requests.

**Comment by Sp0ngeb0bb** [comment]
Hello can u help me how to do it thanks.

**Comment by Sp0ngeb0bb** [comment]
Hello @I2rys, i need help for set it up because i dont know how to do it. My discord name is 

𝕾𝖕𝟎𝖓𝖌𝖊𝖇𝟎𝖇_, thank you so much.

**Comment by I2rys** [comment]
Hello @Sp0ngeb0bb, I can't seem to add you in Discord. Mind adding me instead? My tag is i2rys

**Comment by altvybz** [comment]
> Hello @k9in3 I have added you in Discord, please check your friend requests.

hi mate i think i’ve added you on discord but im having the same issues i’ll explain on there? my discord is altvybz. but i think i have already sent you a friend request.

**Comment by I2rys** [comment]
> > Hello @k9in3 I have added you in Discord, please check your friend requests.
> 
> hi mate i think i’ve added you on discord but im having the same issues i’ll explain on there? my discord is altvybz. but i think i have already sent you a friend request.

Yes and because you have already added me I'll be closing this case.
