### ISSUE TITLE
I need help to run the script

### ISSUE THREAD

**Issue by Arnix1605** [OTAKKATO/ZeroDiscord#39]
Hello, I've been working with this code for several days, honestly, I don't have any experience with any type of work related to programming, and it's costing me a little.

I performed the first step and the second correctly, but when executing the script I get this error that I am going to attach, could you please help me?
![Captura de pantalla 2024-03-29 030459](https://github.com/cspi-git/ZeroDiscord/assets/152509267/15adcb05-2acb-4d8f-b513-bf5094694297)

**Comment by I2rys** [comment]
Hello @Arnix1605, since I'm not that active in Github anymore. Mind adding me in Discord? I would like to help you there. My tag is **I2rys**
